# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00002j0n2qe\tmp\build\80754af9\rsync-recipes\ca-certificates-2021.1.19-on-winbuilder, last modified Mon Mar  8 14:37:23 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.1.19
source:
  fn: cacert.pem
  sha256: e010c0c071a2c79a76aa3c289dc7e4ac4ed38492bfda06d766a80b707ebd2f29
  url: https://curl.haxx.se/ca/cacert-2021-01-19.pem
build:
  commands:
    - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
    - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
    - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
  number: '1'
  string: haa95532_1
requirements:
  build: []
  run: []
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
