# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00002b3bf1u\tmp\build\80754af9\combined_recipe, last modified Mon Jan 25 12:04:44 2021
# ------------------------------------------------

package:
  name: setuptools
  version: 52.0.0
source:
  patches:
    - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
    - 0002-disable-downloads-inside-conda-build.patch
  sha256: ff0c74d1b905a224d647f99c6135eacbec2620219992186b81aa20012bc7f882
  url: https://github.com/pypa/setuptools/archive/v52.0.0.tar.gz
build:
  number: '0'
  string: py37haa95532_0
requirements:
  build: []
  host:
    - ca-certificates 2021.1.19 haa95532_0
    - certifi 2020.12.5 py37haa95532_0
    - openssl 1.1.1i h2bbff1b_0
    - python 3.7.9 h60c2a47_0
    - sqlite 3.33.0 h2a8f88b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wincertstore 0.2 py37_0
    - zlib 1.2.11 h62dcd97_4
  run:
    - certifi >=2016.9.26
    - python >=3.7,<3.8.0a0
    - wincertstore >=0.2
test:
  imports:
    - pkg_resources
    - setuptools
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: http://pythonhosted.org/setuptools/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - nicoddemus
    - ocefpaf
