# This file created by conda-build 3.1.6+534.g828a654f1.dirty
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\wincertstore-feedstock\recipe, last modified Tue Sep 19 15:28:52 2017
# ------------------------------------------------

package:
    name: wincertstore
    version: '0.2'
source:
    fn: wincertstore-0.2.zip
    sha256: 780bd1557c9185c15d9f4221ea7f905cb20b93f7151ca8ccaed9714dce4b327a
    url: https://pypi.io/packages/source/w/wincertstore/wincertstore-0.2.zip
build:
    number: '0'
    script: python setup.py install
    string: py37_0
requirements:
    host:
        - python 3.7.0 hea74fb7_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - wincertstore
about:
    home: https://bitbucket.org/tiran/wincertstore
    license: PSF 2
    license_file: LICENSE
    summary: Python module to extract CA and CRL certs from Windows' cert store (ctypes
        based).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
